title: "[License] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## License & Purchase Support
        For purchase issues, please include your order details.

        **Note**: For privacy, do not share your full license key publicly.

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of help do you need?
      options:
        - Lost license key
        - Activation problem
        - License not working
        - Refund request
        - Purchase question
        - Other
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Purchase Email
      description: The email address used for purchase
      placeholder: "your@email.com"
    validations:
      required: true

  - type: input
    id: order_date
    attributes:
      label: Approximate Purchase Date
      description: When did you make the purchase?
      placeholder: "e.g., January 2026"
    validations:
      required: false

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please describe your issue in detail
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I understand that license support may take 1-2 business days
          required: true
